name: GitHub Classroom Workflow

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 1377ef70dbc2b2d0ffc1fbc14ead9f64128613fb
      - run: |
          repo_pattern="([^-]*)-([^-]*)-([^-]*)-(.*)"
          [[ ${{github.event.repository.name}} =~ $repo_pattern ]]
          git clone https://${{secrets.token}}@github.com/CSCE-313-FA24-Kebo/programming-assignment-2-solution.git tests
          cp -r tests/private-test-files/* ./test-files/
          cp tests/*tests.sh ./
          cp tests/autograding.json .github/classroom/autograding.json
          cp tests/makefile makefile
          make test > ./.gradefile
          make private_test > ./.gradefile_private
      - uses: education/autograding@v1
